quarkus:
  application:
    name: paypulse

  http:
    port: 8080
    cors: true
    cors-origins: "*"
    cors-methods: GET,POST,PUT,DELETE,OPTIONS

  log:
    level: INFO

  smallrye-openapi:
    path: /openapi

  health:
    openapi:
      included: true

  %dev:
     quarkus:
       log:
         level: DEBUG

  %test:
     quarkus:
       log:
         level: WARN

  %prod:
     quarkus:
       log:
         level: INFO
